### ISSUE TITLE
ke 1ehz a regression test for the new SuiteName

### ISSUE THREAD

**Issue by russell-taylor** [ReliaSolve/cctbx_project#78] opened 2021-06-30 15:01 UTC

**Comment by Joymaker** [comment] 2021-07-13 18:21
I have a draft version of this that runs successfully on Windows. Need to do a little more shell scripting for other operating systems. Perhaps we should have a discussion about the what the whole testing package looks like, how unit testing and regression testing will be integrated in normal practice.

**Comment by russell-taylor** [comment] 2021-07-14 13:11
Yes we should.  This will go into the CCTBX standard approach, which will be Python scripts not shell scripts.  My shell scripts are intended to be thrown away once we know the new code works as well as the old.

**Comment by russell-taylor** [comment] 2021-07-14 13:14
See the mmtbx/probe/tst_probe.py script in reliasolve/cctbx_project in the native-probe branch for an example of how to incorporate the unit tests, which will also include regression tests in our case.

**Comment by Joymaker** [comment] 2021-07-22 13:59
I have rationalized unit testing and regression testing so that they are now all one thing, including 1ehz and easily expandable to include other files as desired.

This process triggered the use of suites.py as a library, which triggered substantial debugging and rationalizing of the method for supplying options. All this now appears to be working smoothly.

**Closed** 2021-07-22 13:59 UTC
